//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komunikator_z_PKI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_znajomych
    {
        public int id_znajomosci { get; set; }
        public int id_uzytkownika { get; set; }
        public int id_znajomego { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        public virtual Uzytkownicy Uzytkownicy1 { get; set; }
    }
}
