//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komunikator_z_PKI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoipEntities : DbContext
    {
        public VoipEntities()
            : base("name=VoipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Historia> Historia { get; set; }
        public virtual DbSet<Lista_znajomych> Lista_znajomych { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
